#!/bin/bash

SCRIPT_PATH="$( cd "$(dirname "$0")" ; pwd -P )"
SCRIPT_PATH="$(realpath $SCRIPT_PATH)"

user_install=
[ "$1" ] && {
  [ "$1" == "user" ] && {
    user_install=1
  }
}

SUDO=sudo
if [ "${EUID}" ]; then
  [ ${EUID} -eq 0 ] && SUDO=
else
  uid=$(id -u)
  [ ${uid} -eq 0 ] && SUDO=
fi

install_borg() {
  # Releases:
  #   borg-freebsd64
  #   borg-linux64
  #   borg-macos64
  # Currently borgsync only supports macos and linux
  relname="linux64"
  [ "$platform" == "Darwin" ] && relname="macos64"
  API_URL="https://api.github.com/repos/borgbackup/borg/releases/latest"
  DL_URL=
  DL_URL=$(curl --silent ${AUTH_HEADER} "${API_URL}" \
    | jq --raw-output '.assets | .[]?.browser_download_url' \
    | grep "borg-${relname}$")

  [ "${DL_URL}" ] && {
    printf "\n\tInstalling Borg ..."
    wget --quiet -O /tmp/borg$$ "${DL_URL}"
    chmod 644 /tmp/borg$$
    [ -d /usr/local/bin ] || ${SUDO} mkdir -p /usr/local/bin
    ${SUDO} cp /tmp/borg$$ /usr/local/bin/borg
    ${SUDO} chown root:${group} /usr/local/bin/borg
    ${SUDO} chmod 755 /usr/local/bin/borg
    ${SUDO} ln -s /usr/local/bin/borg /usr/local/bin/borgfs
    rm -f /tmp/borg$$
    printf " done"
  }
}

install_vort() {
  printf "\n\tInstalling Vorta ..."
  have_pipx=$(type -p pipx)
  if [ "${have_pipx}" ]; then
    pipx install vorta >/dev/null 2>&1
  else
    python3 -m pip install vorta >/dev/null 2>&1
  fi
  [ -f ${SCRIPT_PATH}/share/vorta.desktop ] && {
    [ -d ${HOME}/.local ] || mkdir -p ${HOME}/.local
    [ -d ${HOME}/.local/share ] || mkdir -p ${HOME}/.local/share
    [ -d ${HOME}/.local/share/applications ] || {
      mkdir -p ${HOME}/.local/share/applications
    }
    cp ${SCRIPT_PATH}/share/vorta.desktop ${HOME}/.local/share/applications
    chmod 755 ${HOME}/.local/share/applications/vorta.desktop
  }
  printf " done"
}

if [ "${GH_TOKEN}" ]; then
  AUTH_HEADER="-H \"Authorization: Bearer ${GH_TOKEN}\""
else
  AUTH_HEADER=
fi

have_pipx=$(type -p pipx)
if [ "${have_pipx}" ]; then
  pipx ensurepath >/dev/null 2>&1
  pipx install rich-cli >/dev/null 2>&1
else
  python3 -m pip install rich-cli >/dev/null 2>&1
fi

platform=$(uname -s)
group="root"
cfdir="config"
[ "$platform" == "Darwin" ] && {
  group="wheel"
  cfdir="config/macos"
}
have_borg=$(type -p borg)
[ "${have_borg}" ] || install_borg
have_vort=$(type -p vorta)
[ "${have_vort}" ] || install_vort

[ -d /etc/borgsync ] || ${SUDO} mkdir -p /etc/borgsync
if [ "${user_install}" ]; then
  [ -d ${HOME}/.local/bin ] || mkdir -p ${HOME}/.local/bin
  cp ${SCRIPT_PATH}/bin/borgsync ${HOME}/.local/bin/borgsync
  chmod 755 ${HOME}/.local/bin/borgsync

  [ -d ${HOME}/.config/borgsync ] || mkdir -p ${HOME}/.config/borgsync
  for cfg in ${SCRIPT_PATH}/${cfdir}/*
  do
    [ "${cfg}" == "${SCRIPT_PATH}/${cfdir}/*" ] && continue
    [ -d "${cfg}" ] && continue
    [ "${cfg}" == "${SCRIPT_PATH}/${cfdir}/README.md" ] && {
      cp ${cfg} ${HOME}/.config/borgsync
      continue
    }
    confname=$(basename "${cfg}")
    if [ -f ${HOME}/.config/borgsync/${confname} ]; then
      diff ${cfg} ${HOME}/.config/borgsync/${confname} > /dev/null && {
        cp ${cfg} ${HOME}/.config/borgsync/${confname}.orig
      }
    else
      cp ${cfg} ${HOME}/.config/borgsync
    fi
  done
  chmod 755 ${HOME}/.config/borgsync
  chmod 644 ${HOME}/.config/borgsync/*
else
  ${SUDO} cp ${SCRIPT_PATH}/bin/borgsync /usr/local/bin/borgsync
  ${SUDO} chown root:${group} /usr/local/bin/borgsync
  ${SUDO} chmod 755 /usr/local/bin/borgsync

  for cfg in ${SCRIPT_PATH}/${cfdir}/*
  do
    [ "${cfg}" == "${SCRIPT_PATH}/${cfdir}/*" ] && continue
    [ -d "${cfg}" ] && continue
    [ "${cfg}" == "${SCRIPT_PATH}/${cfdir}/README.md" ] && {
      ${SUDO} cp ${cfg} /etc/borgsync
      continue
    }
    confname=$(basename "${cfg}")
    if [ -f /etc/borgsync/${confname} ]; then
      ${SUDO} diff ${cfg} /etc/borgsync/${confname} > /dev/null || {
        ${SUDO} cp ${cfg} /etc/borgsync/${confname}.orig
      }
    else
      ${SUDO} cp ${cfg} /etc/borgsync
    fi
  done
  ${SUDO} chmod 755 /etc/borgsync
  ${SUDO} chown root:${group} /etc/borgsync/*
  ${SUDO} chmod 644 /etc/borgsync/*
fi
${SUDO} cp ${SCRIPT_PATH}/VERSION /etc/borgsync

printf "\n\nInstallation of borgsync complete ✨ 🌟 ✨\n"
printf "\nCustomize the borgsync configuration file:"
printf "\n\t# set your remote storage user/host, paths, etc"
if [ "${user_install}" ]; then
  printf "\n\tvi ${HOME}/.config/borgsync/base\n"
else
  printf "\n\t${SUDO} vi /etc/borgsync/base\n"
fi

printf "\nSetup password-less ssh access to your remote storage service"
printf "\nSee https://github.com/doctorfree/borgsync#requirements for details\n"

printf "\nInitialize a Borg repository for home directory backups:"
printf "\n\tborgsync -b init -t home\n"

printf "\nExport your Borg passphrase in the environment:"
printf "\n\texport BORG_PASSPHRASE='somelongphrase'"
printf "\nCreate a Borg backup of the home directories:"
printf "\n\tborgsync -b create -t home\n"

printf "\nView usage and configure automated backups:"
printf "\nSee https://github.com/doctorfree/borgsync#usage\n"
