#!/bin/bash

SCRIPT_PATH="$( cd "$(dirname "$0")" ; pwd -P )"
SCRIPT_PATH="$(realpath $SCRIPT_PATH)"

SUDO=sudo
if [ "${EUID}" ]; then
  [ ${EUID} -eq 0 ] && SUDO=
else
  uid=$(id -u)
  [ ${uid} -eq 0 ] && SUDO=
fi

install_borg() {
  API_URL="https://api.github.com/repos/borgbackup/borg/releases/latest"
  DL_URL=
  DL_URL=$(curl --silent ${AUTH_HEADER} "${API_URL}" \
    | jq --raw-output '.assets | .[]?.browser_download_url' \
    | grep "borg-linux64$")

  [ "${DL_URL}" ] && {
    printf "\n\tInstalling Borg ..."
    wget --quiet -O /tmp/borg$$ "${DL_URL}"
    chmod 644 /tmp/borg$$
    [ -d /usr/local/bin ] || ${SUDO} mkdir -p /usr/local/bin
    ${SUDO} cp /tmp/borg$$ /usr/local/bin/borg
    ${SUDO} chown root:root /usr/local/bin/borg
    ${SUDO} chmod 755 /usr/local/bin/borg
    ${SUDO} ln -s /usr/local/bin/borg /usr/local/bin/borgfs
    rm -f /tmp/borg$$
    printf " done"
  }
}

if [ "${GH_TOKEN}" ]; then
  AUTH_HEADER="-H \"Authorization: Bearer ${GH_TOKEN}\""
else
  AUTH_HEADER=
fi

have_borg=$(type -p borg)
[ "${have_borg}" ] || install_borg

${SUDO} cp ${SCRIPT_PATH}/bin/borgsync /usr/local/bin/borgsync
${SUDO} chown root:root /usr/local/bin/borgsync
${SUDO} chmod 755 /usr/local/bin/borgsync

[ -d /etc/borgsync ] || ${SUDO} mkdir -p /etc/borgsync
${SUDO} cp ${SCRIPT_PATH}/config.example /etc/borgsync

printf "\nInstallation of borgsync complete"
printf "\nCustomize and install the borgsync configuration file:\n"

printf "\n${SUDO} cp /etc/borgsync/config.example /etc/borgsync/config"
printf "\n${SUDO} vi /etc/borgsync/config    # add your rsync.net user/host, paths, etc"
printf "\n${SUDO} chown root:root /etc/borgsync/config"
printf "\n${SUDO} chmod 644 /etc/borgsync/config\n"

printf "\nExport your Borg passphrase in the environment:"
printf "\n\texport BORG_PASSPHRASE='somelongphrase'\n"

printf "\nOptionally configure automated backups with systemd or cron"
printf "\nby following the instructions in the README\n"
